### ISSUE TITLE
Admin Report Only Works on Mondays

### ISSUE THREAD

**Issue by sonoracomm** [wuxmedia/Zimbra_passpoll#4]
Hello and thank you very much for this script.  Zimbra apparently lacks the important ability to notify users of expiring passwords.  Seems crazy to me...

I have implemented your script in a trial manner.

It appears that, while the Zimbra Admin receives an e-mail every day titled "List of accounts with expired passwords", it only contains actual data on Mondays!

Perhaps I have implemented something wrong?

Do you have any suggestions for me on what to check?

I have Zimbra OSE 8.8.12 on CentOS 7.

Thanks,

G

**Comment by wuxmedia** [comment]
This was in my original brief for the script. The code you need to look at is here, the comment is in the code:
```
# Check for Expired accounts, get last logon date add them to EXP_LIST2 every monday
elif [[ "$DEADLINE" -lt "0" ]] && [ "$(date +%a)" = "Mon" ]
```
You would need to alter that, probably just remove ```&& [ "$(date +%a)" = "Mon" ]``` but I haven't tested that, use at your own risk :D

**Comment by sonoracomm** [comment]
Hi and thanks again!

Removing that part does appear to have fixed the issue.
`&& [ "$(date +%a)" = "Mon" ]`
Hopefully, I didn't introduce another problem.

Cheers,

G
